name: test

on: [push]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Setup Lua
      uses: leafo/gh-actions-lua@v9
    -
      name: Setup Luarocks
      uses: leafo/gh-actions-luarocks@v4
    -
      name: Install Tools
      run: luarocks install luacheck
    -
      name: Run luacheck
      run: |
        luacheck .

  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:6
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    strategy:
      matrix:
        lua-version:
          - "5.1"
          - "5.2"
          - "5.3"
          - "5.4"
          - "luajit-2.0.5"
          - "luajit-openresty"

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    -
      name: Install Required Packages
      run: |
        sudo apt install libtls-dev -y
    -
      name: Cache lua modules
      id: cache-luarocks
      uses: actions/cache@v3
      with:
        path: .luarocks
        key: ${{ runner.os }}-${{ matrix.lua-version }}-cache-${{ hashFiles('rockspecs/redis-scm-1.rockspec') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.lua-version }}-cache-
    -
      name: Remove must re-installation modules
      run: |
        luarocks remove errno --force || true
        luarocks remove error --force || true
        luarocks remove iovec --force || true
        luarocks remove lauxhlib --force || true
    -
      name: Setup Lua ${{ matrix.lua-version }}
      uses: leafo/gh-actions-lua@v9
      with:
        luaVersion: ${{ matrix.lua-version }}
    -
      name: Setup Luarocks
      uses: leafo/gh-actions-luarocks@v4
      with:
        luarocksVersion: "3.8.0"
    -
      name: Install
      run: |
        luarocks install testcase
        luarocks install luacov
        luarocks make
    -
      name: Run Test
      run: |
        testcase --coverage ./test/
    -
      name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        flags: unittests
